---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sklearn-helm
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https:https://github.com/Sangauppe/sklearn-helm/tree/main
